theme: jekyll-theme-minimal
title: Zihan Gao
logo: imgs/IMG_6627.JPG
description: "PhD Student
  <br>Information School
  <br>University of Wisconsin-Madison
  <br>Madison, WI 53706
  <br>
  <br>Email: zihan [dot] gao [at] wisc [dot] edu"
  <br>
  <br><a href=\"https://www.linkedin.com/in/zihan-gao-520a92252/\">Linkedin</a>
