theme: jekyll-theme-minimal
title: Zihan Gao
logo: zihan_head_pro.JPG
description: "PhD Candidate
  <br>Information School
  <br>University of Wisconsin-Madison
  <br>Madison, WI 53706
  <br>
  <br>Email: zihan [dot] gao [at] wisc [dot] edu
  <br>
  <br><a href=\"https://scholar.google.com/citations?user=ZWC-IxkAAAAJ&hl=en&oi=sra\">Google Scholar</a>
  <br><a href=\"https://www.linkedin.com/in/zihan-gao-520a92252\">Linkedin</a>"
  
  
